// Draw a button with Swing. Click the button mouse icon into a cross, click again, into the gesture icon
, and release. If the button is square, the user can press and hold the button until the end of the gesture. If the button is round, the user should be able to move the mouse cursor while the button is pressed and release it. Use the space bar to activate the button and press and hold the button for as long as the button is active. Stop drawing when the mouse cursor leaves the button area.
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class Button extends JPanel {
    final int crossSize = 10;
    final int margin = 20;
    final int buttonSize = 150;
    final int buttonGap = 20;
    final int buttonMargin = 20;
    final int buttonX = buttonMargin;
    final int buttonY = buttonMargin;
    final int buttonWidth = buttonSize + 2 * buttonMargin;
    final int buttonHeight = buttonSize + 2 * buttonMargin;
    final int buttonX2 = buttonX + buttonWidth;
    final int buttonY2 = buttonY + buttonHeight;
    final int buttonX3 = buttonX2 + buttonGap;
    final int buttonY3 = buttonY2;
    final int buttonX4 = buttonX2 + 2 * buttonGap;
    final int buttonY4 = buttonY3;
    final int buttonX5 = buttonX4 + buttonGap;
    final int buttonY5 = buttonY4;
    final int buttonX6 = buttonX5 + buttonGap;
    final int buttonY6 = buttonY5;
    final int buttonX7 = buttonX6 + buttonGap;
    final int buttonY7 = buttonY6;
    final int buttonX8 = buttonX7 + buttonGap;
    final int buttonY8 = buttonY7;
    final int buttonX9 = buttonX8 + buttonGap;
    final int buttonY9 = buttonY8;
    final String cross = "\u2716";
    final String cross2 = "\u23ce";
    final String cross3 = "\u2717";
    final String cross4 = "\u23cf";
    final String cross5 = "\u27f8";
    final String cross6 = "\u27f9";
    final String cross7 = "\u27f3";
    final String cross8 = "\u27f4";
    final String cross9 = "\u27f7";
    final String cross10 = "\u27f2";
    final String cross11 = "\u27f1";
    final String cross12 = "\u27f0";
    final String cross13 = "\u27f5";
    final String cross14 = "\u27f6";
    final String cross15 = "\u27f7";
    final String cross16 = "\u27f8";
    final String cross17 = "\u27f9";
    final String cross18 = "\u27f5";
    final String cross19 = "\u27f6";
    final String cross20 = "\u27f7";
    final String cross21 = "\u27f8";
    final String cross22 = "\u27f9";
    final String cross23 = "\u27f3";
    final String cross24 = "\u27f4";
    final String cross25 = "\u27f7";
    final String cross26 = "\u27f9";
    final String cross27 = "\u27f6";
    final String cross28 = "\u27f2";
    final String cross29 = "\u27f1";
    final String cross30 = "\u27f0";
    final String cross31 = "\u27f5";
    final String cross32 = "\u27f6";
    final String cross33 = "\u27f7";
    final String cross34 = "\u27f8";
    final String cross35 = "\u27f9";
    final String cross36 = "\u27f5";
    final String cross37 = "\u27f6";
    final String cross38 = "\u27f7";
    final String cross39 = "\u27f8";
    final String cross40 = "\u27f9";
    final String cross41 = "\u27f3";
    final String cross42 = "\u27f4";
    final String cross43 = "\u27f7";
    final String cross44 = "\u27f9";
    final String cross45 = "\u27f6";
<h1><p>Bad Request</p></h1>