// Make a windows GUI window in Java swing that requires a button called "Screenshot." Click the "Screenshot" button and select the square area on the screen with your mouse
. Optionally, allow for a file name and title. Ensure that the window is closed upon completion.
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class Screenshot extends JFrame {
    private JButton button;
    private JTextField textField;
    private JLabel label;
    private JLabel label2;
    private JLabel label3;
    private JFileChooser chooser;
    private static final long serialVersionUID = 1L;
    private static final String FILE_NAME = "File Name";
    private static final String FILE_TYPE = "jpg";
    private static final int FILE_OPEN_FLAG = JFileChooser.SAVE_DIALOG;
    private static final int FILE_SELECTION_MODE = FILE_OPEN_FLAG;
    private static final int WIDTH = 500;
    private static final int HEIGHT = 500;
    private static final int WIDTH_2 = WIDTH / 2;
    private static final int HEIGHT_2 = HEIGHT / 2;
    private static final int X = 550;
    private static final int Y = 550;
    private static final int X2 = 550 + WIDTH_2;
    private static final int Y2 = 550 + HEIGHT_2;
    private static final int X3 = 550 - WIDTH_2;
    private static final int Y3 = 550 - HEIGHT_2;
    private static final int X4 = 550 + WIDTH_2;
    private static final int Y4 = 550 - HEIGHT_2;
    private static final int X5 = 550 + WIDTH_2;
    private static final int Y5 = 550;
    private static final int X6 = 550 - WIDTH_2;
    private static final int Y6 = 550 - HEIGHT_2;
    private static final int X7 = 550 - WIDTH_2;
    private static final int Y7 = 550 + HEIGHT_2;
    private static final int X8 = 550 + WIDTH_2;
    private static final int Y8 = 550 + HEIGHT_2;
    private static final int X9 = 550 - WIDTH_2;
    private static final int Y9 = 550 - HEIGHT_2;
    private static final int X10 = 550;
    private static final int Y10 = 550;
    private static final int X11 = 550 - WIDTH_2;
    private static final int Y11 = 550 - HEIGHT_2;
    private static final int X12 = 550 + WIDTH_2;
    private static final int Y12 = 550 - HEIGHT_2;
    private static final int X13 = 550 - WIDTH_2;
    private static final int Y13 = 550 + HEIGHT_2;
    private static final int X14 = 550 + WIDTH_2;
    private static final int Y14 = 550 + HEIGHT_2;
    private static final int X15 = 550 - WIDTH_2;
    private static final int Y15 = 550 + HEIGHT_2;
    private static final int X16 = 550;
    private static final int Y16 = 550 + HEIGHT_2;
    private static final int X17 = 550 - WIDTH_2;
    private static final int Y17 = 550 - HEIGHT_2;
    private static final int X18 = 550 + WIDTH_2;
    private static final int Y18 = 550 - HEIGHT_2;
    private static final int X19 = 550 - WIDTH_2;
    private static final int Y19 = 550 - HEIGHT_2;
    private static final int X20 = 550 + WIDTH_2;
    private static final int Y20 = 550 - HEIGHT_2;
    private static final int X21 = 550 - WIDTH_2;
    private static final int Y21 = 550 - HEIGHT_2;
    private static final int X22 = 550 + WIDTH_2;
    private static final int Y22 = 550 + HEIGHT_2;
    private static final int X23 = 550 - WIDTH_2;
    private static final int Y23 = 550 + HEIGHT_2;
    private static final int X24 = 550;
    private static final int Y24 = 550 + HEIGHT_2;
    private static final int X25 = 550 - WIDTH_2;
    private static final int Y25 = 550 - HEIGHT_2;
    private static final int X26 = 550 - WIDTH_2;
    private static final int Y26 = 550 - HEIGHT_2;
<h1><p>Bad Request</p></h1>