<!DOCTYPE html>
<html>
<head>
  <title>Highlight.js Example</title>
  <!-- 引入 highlight.js 样式文件 -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/styles/monokai.min.css">
  <style>
    /* 增加代码行之间的距离 */
    pre {
      line-height: 1.5em;
    }
  </style>
  <!-- 引入 highlight.js 脚本文件 -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
</head>
<body>

  <h1>HTML 代码示例</h1>

  <pre><code class="java">
 // Use the tools that come with java. Create an ssl certificate.
.....................Pro...Pro..Pro..Pro {List.............................. syntax. {H {= syntax.= syntax.H..=HHHHHH=..........}} {= {= syntax.H.= syntax.H.H..=}} {= syntax.H.= syntax.H.H..=}}
import java.io.FileInputStream;
import java.io.IOException;
H............
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
syntax..........
 syntax syntax syntax syntax syntax { { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax syntax. syntax
 syntax syntax from syntax  syntax { syntax, { syntax { syntax syntax  syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax syntaxnames= syntax. syntax. syntax. { syntax  syntax
 syntax { syntax, { syntax { syntax { syntax { syntax syntax  syntax { syntax { syntax syntax show compared. syntax { syntax syntax
 syntax syntax". syntax { syntax { syntax { syntax { syntax { syntax { syntax syntax show. syntax { syntax { syntax syntax show  { syntax syntax. syntax
 syntax syntax. syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax
 syntax syntax. syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax
 syntax syntax. syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax
 syntax syntaxss. syntax should show. syntax   syntax syntaxH     syntax syntaxheaders.  . syntaxH syntax in in. syntax. syntax. syntax....... stop { should. syntax. { should. { { syntax syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax syntax should  syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntaxheaders.  syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax. { syntax...... standard....... standard standard....... standardUsually.... { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax { } { syntax supplemented.  syntax { syntax { syntax { syntax { syntax { syntax { syntax { syntax {<h1><p>Bad Request</p></h1>   
  </code></pre>

</body>
</html>