version: '3'
services:
  tomcat_war:
    image: registry.cn-shanghai.aliyuncs.com/00fly/docker-run:latest
    container_name: docker-run
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100M
        reservations:
          cpus: '0.05'
          memory: 20M
    ports:
    - 18080:8080
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-file: 1
        max-size: 5m