version: '3'
services:
  tomcat_war:
    image: registry.cn-shanghai.aliyuncs.com/00fly/dbtool_simple
    container_name: dbtool
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M
        reservations:
          memory: 200M
    ports:
      - 18080:8080
    restart: on-failure
    logging:
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '1'