#基础镜像
FROM tomcat:alpine

#设置字符集
ENV LANG en_US.UTF-8

#设置时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

WORKDIR /usr/local/tomcat/webapps/

RUN rm -rf *
COPY *.war  ROOT.war

#Expose http port
EXPOSE 8080
